# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
  pull_request:
  merge_group:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.version }}
    - name: Setup pnpm
      # You may pin to the exact commit or the version.
      # uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
      uses: pnpm/action-setup@v4.0.0
      with:
        # If specified, run `pnpm install`
        run_install: true
    - run: pnpm test
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.6.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
